#!/bin/bash

function doIt () {
	sudo -v
	source ~/dotfiles/install.sh
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	doIt;
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
	echo '';
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		doIt;
	else
		echo "Canceled";
		exit 1
	fi;
fi;
unset doIt;